[package]
name = "verilogy"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[build-dependencies]
lalrpop = "0.22.1"

[dependencies]
lalrpop-util = { version = "0.22.1", features = ["lexer", "unicode"] }